language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy3
install:
  - pip install coverage coverage-python-version coveralls
script:
  - coverage run testsuite.py
after_script:
  - coveralls

matrix:
  include:
    - name: flake8
      install: pip install flake8
      script: flake8 *.py
      after_script:

notifications:
  irc:
    channels:
      - "chat.freenode.net##mgedmin"
    on_success: change
    on_failure: always
    template:
      # ping my nick so I get a pushbullet notification on my phone
      - "mgedmin: %{repository_name} (%{branch}) build %{result}: %{build_url}"
