language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install coverage coveralls
script:
    - coverage run --source=findimports testsuite.py
after_script:
    - coveralls
notifications:
    email: false
