name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 6"  # 5:00 UTC every Saturday

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 2.7
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - pypy2
          - pypy3

    steps:
      - name: Git clone
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools wheel
          python -m pip install -U coverage coverage-python-version flake8

      - name: Run flake8
        run: |
          flake8 *.py

      - name: Run tests
        run: |
          coverage run testsuite.py

      - name: Check test coverage
        run: |
          coverage report -m --fail-under=100
